;;; vterm-hotkey-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vterm-hotkey.el

(autoload 'vterm-hotkey "vterm-hotkey" "\
Create or switch to a `vterm-hotkey' buffer associated with KEY.

(fn KEY)" t)
(register-definition-prefixes "vterm-hotkey" '("vterm-hotkey-"))

;;; End of scraped data

(provide 'vterm-hotkey-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vterm-hotkey-autoloads.el ends here
